### ISSUE TITLE
Verify JDK8 install on Windows

### ISSUE THREAD

**Issue by tmarble** [clojurebridge-minneapolis/installfest#10]
We need to check the URL's, verify the install procedure, etc.

See also:
https://github.com/clojurebridge-minneapolis/installfest/blob/experimental/docs/setup_new_java.md 

Will contribute to #8

**Comment by GregA100k** [comment]
Java files to download now have version numbers in the filenames which does not seem worth the time to chage.  Other than that, Java 8 install instructions on WIndows look good.

**Comment by tmarble** [comment]
Closed by @GregA100k in https://github.com/clojurebridge-minneapolis/installfest/commit/3d4044d869b2e824614a9f96b80e109c76fd1b37
