### ISSUE TITLE
Verify Nightcode install on Mac

### ISSUE THREAD

**Issue by tmarble** [clojurebridge-minneapolis/installfest#12]
We need to check the URL's, verify the install procedure, etc.
- Verify lein is bundled in (anything else bundled??)
- Figure out how to change font size.

See also:
https://sekao.net/nightcode/
https://github.com/clojurebridge-minneapolis/installfest/blob/experimental/docs/setup_new_lein.md 

Will contribute to #8

**Comment by skoestler** [comment]
Their site says that leiningen and boot are both bundled.
The font size can be configured in the "Start" dropdown menu.

**Comment by mulchy** [comment]
@skoestler thanks for verifying this and updating the docs!

**Comment by mulchy** [comment]
Reopening this because we still need to update these instructions https://github.com/clojurebridge-minneapolis/installfest/blob/master/docs/setup_osx.md

**Comment by mulchy** [comment]
I have started moving the docs @skoestler added to the setup OSX file, but still need to update the `Testing Your Setup` section.

**Comment by brian-dawn** [comment]
Closing because we use atom now.
