### ISSUE TITLE
Verify Heroku install on Mac

### ISSUE THREAD

**Issue by tmarble** [clojurebridge-minneapolis/installfest#15]
We need to check the URL's, verify the install procedure, etc.
- IIRC this has some git + ssh functionality?
- Smoke check that some kind of "hello world" still works

See also:
https://github.com/clojurebridge-minneapolis/installfest/blob/experimental/docs/setup_new_heroku.md 

Will contribute to #8

**Comment by MageMasher** [comment]
Hey @tmarble @mulchy , I ran through this and it seems to work. 

I downloaded the mac installer and ran through their instructions. 
I dont have an app that can easily be run on heroku right now, however when i ran `heroku create` it gave me a url I could hit with their hello world page. 

Is that good enough?
