### ISSUE TITLE
Verify Heroku install on Windows

### ISSUE THREAD

**Issue by tmarble** [clojurebridge-minneapolis/installfest#16]
We need to check the URL's, verify the install procedure, etc.
- IIRC this has some git + ssh functionality?
- Smoke check that some kind of "hello world" still works
- Do we need gitbash???

See also:
https://github.com/clojurebridge-minneapolis/installfest/blob/experimental/docs/setup_new_heroku.md 

Will contribute to #8

**Comment by GregA100k** [comment]
Account setup has added an email verification step.  I added screenshots for that to the windows 10 instructions.  I'll update windows 7 and 8 instructions to match after the trick or treaters are done.

The 'some kind of "hello world"' is different on linux (clojure-getting-started.git) than on OSX and windows (clojure-sample.git).  I have verified clojure-sample.git on windows 10.

**Comment by tmarble** [comment]
Closed by @GregA100k in https://github.com/clojurebridge-minneapolis/installfest/commit/3d4044d869b2e824614a9f96b80e109c76fd1b37
