### ISSUE TITLE
Dogfood Track 2: koans

### ISSUE THREAD

**Issue by tmarble** [clojurebridge-minneapolis/installfest#21]
The goal of this ticket is to walk through Track 2 koans a student and ensure things are up-to-date and easy to understand.

See also
https://github.com/clojurebridge-minneapolis/installfest/blob/experimental/docs/setup_new_koans.md

File issues in koans repo as needed

**Comment by tmarble** [comment]
I did a diff vs. upstream koans and briand is right.. they took all of our suggestions.. so i brought https://github.com/clojurebridge-minneapolis/clojure-koans up to date with upstream 

Then I tried to run the koans in Nightcode on Linux. Here's the issues I ran into
1. I can import the koans project, but when I navigate to src -> koans the files are listed out of order (?)
2. In other projects I can use the Nightcode REPL fine, but when I click "Run with REPL" my return key does not work (this is super annoying). Normally I used to be able to start the exercises with `(exec "run")`. As a workaround a did `lein koan run` in a separate terminal window.
3. For some reason Nightcode doesn't recognize editing the file and enabling the **Save** button ?!!! These seems to work fine in other projects... Please see if this works for you. I found a workaround: import the project, use the workaround from step 2 above, but do NOT press any of the Run buttons in Nightcode (then autosave just works).

NOTE: Here are the upstream URL's
- https://github.com/functional-koans/clojure-koans
- http://clojurekoans.com/

**Comment by brian-dawn** [comment]
For track 2 we don't have to use nightcode - since the koan test runner is ran from the terminal I almost feel like it might be easier to use atom/sublime text.

**Comment by tmarble** [comment]
@brian-dawn would atom/sublime be the _cross platform_ recommendation?
I'm fine with that (of course we'd need to add the step to each platform's install instructions).
Otherwise do you think we can close this issue?

**Comment by brian-dawn** [comment]
@tmarble yes it's cross platform I run it on all 3 OSs.

We can update each installfest doc, or we can have students use nightcode for now and just recommend in person that if they prefer they can try atom - I'm averse to too much change close to the event. Does that work? Because if so we can close this issue.

**Comment by tmarble** [comment]
Works for me.
