### ISSUE TITLE
Prepare a 15 minute intro to git

### ISSUE THREAD

**Issue by tmarble** [clojurebridge-minneapolis/installfest#23]
We've observed that students struggle with git.

It's worth spending 15 minutes at the top of the workshop to explain the basic concepts of git -- what and why we're using git (and why it's cool to collaborate on github).

The goal of this ticket is to prepare a presentation (slides?) and be ready to give it ClojureBridge.

We can point to conventional docs like:
https://git-scm.com/doc

And new edgy docs like:
http://ohshitgit.com/

**Comment by tmarble** [comment]
Note: it will be important to define actions like
- "create repository"
- "push repository"

See also https://github.com/clojurebridge-minneapolis/track1-chatter/issues/49

**Comment by brian-dawn** [comment]
Closing this ticket because it appears to be done!
