### ISSUE TITLE
Create the YOU ARE HERE infographic

### ISSUE THREAD

**Issue by tmarble** [clojurebridge-minneapolis/installfest#25]
Before we give an intro to git #23 we should have a 5 minute (at least) presentation (maybe a handout) which
- defines terms we'll be using a lot
- has a "boxology" of the moving parts we'll be learning about
- somehow explains how all the things students learn will fit together

We may revise this after dogfooding the tracks a couple times (that's fine).

See also
https://github.com/clojurebridge-minneapolis/installfest/blob/master/docs/glossary.md

**Comment by meta-meta** [comment]
I have a friend @williamlfish who's a talented graphic artist and a fledgling developer who is down to whip up some vector graphics for this. What do we want to cover? Here's a start:
- Git
  - version control software
  - auditable history of changes to source code
  - makes sharing and collaboration "easy"
- Heroku
  - a server in the clouds
  - a Virtual Machine that runs a Virtual Machine (JVM)
- Java
  - Java(language): a C-style programming language that compiles to byte code
  - Java Virtual Machine: interprets byte code, runs your compiled program
  - JDK: everything needed to compile Java to byte code and run it
- Clojure
  - a Common Lisp
  - implemented in Java(language) and runs on JVM
- REPL
- Nightcode IDE

**Comment by tmarble** [comment]
@meta-meta this sounds like a fantastic idea! Are we talking vector graphics as in SVG (e.g. in Inkscape)?

This is a challenge to convey, graphically, but i think it will be super powerful.

Ideas to represent (if possible):
- We also need to somehow clarify the the relationship between git and github (or gitlab).
- Relationship between the users app on the laptop ... which is pushed to git... then pulled by Heroku

OMG Clojure is so NOT a Common Lisp. It is an (opinionated) Lisp which has been influenced by a long history of computer languages going back to the first Lisp implementation in 1954. It is implemented for several targets: Java (the JVM), JavaScript, and the CLR.

**Comment by meta-meta** [comment]
Yes, most likely svg. Whoops *uncommon Lisp. Just writing a catch phrase
without thinking about what it means.

**Comment by mulchy** [comment]
Did anything happen with this?

**Comment by meta-meta** [comment]
No, I should have updated. William had a baby last week, so he didn't have time. I was thinking of putting something together today but not sure if I'll get to it.
