### ISSUE TITLE
Who can bring backup laptops?

### ISSUE THREAD

**Issue by tmarble** [clojurebridge-minneapolis/installfest#27]
Please comment here if you can bring a backup laptop.

If possible add:
- CPU, RAM specs
- OS and version
- Did you install all the things yet?

**Comment by mulchy** [comment]
I have an old Macbook Air that has everything installed, but the battery is kind of shot so it would probably need to be plugged in.

Don't remember the OS version or the specs, but I can edit this when I get home.

**Comment by peterschwarz** [comment]
I've got an old MB Pro I can bring.  

It has Yosemite on it, and most of the tools (minus Nightcode).

**Comment by MageMasher** [comment]
I have an old Linux system.
- i7 Quad core, 16 GB Ram
- Ubuntu, Recent Version
- No I did not install the things yet

**Comment by tmarble** [comment]
I think we're covered!
