### ISSUE TITLE
Review ReadTheDocs and merge old and new setup docs

### ISSUE THREAD

**Issue by futuro** [clojurebridge-minneapolis/installfest#30]
# Overview

To really leverage the benefits of ReadTheDocs (or just compiling the documentation with Sphinx and hosting it somewhere else) we need merge the old setup documentation with the new setup documentation, and decide how we want to structure it all.
## Major differences

The old documentation collects the steps based on OS whereas the new documentation collects the steps by what's actually going on. For example, the steps for setting up Heroku in the old docs exist in three places, one per OS, and in one place in the new documentation.

The old documentation is currently more complete, though somewhat out-dated -- it includes steps for installing Lightable, f.e. -- and it includes lots of pictures, which potentially reduces our work load.
## My thoughts

Now that we have the ability to have a sidebar which gives us the context and overview of the steps we need to take, I think the old documentation makes more sense. From the perspective of a student, when I'm trying to figure out how to get everything set up for my OS I don't have to filter what I'm reading based on my OS, instead I'm able to read straight through the docs.

The downside of this approach is that potentially we have to replicate information, which is bad, but the installation paths are so different for each OS that we'd end up having slightly different instructions for each step anyways. Like, "Install Git" is completely different on each OS, so there's no overlapping instructions there.

**Comment by tmarble** [comment]
It turns out RTD is fantastic. The dynamic leftnav solves so many navigation problems.

After a whole bunch of commits the new structure is in place -- including a robot to update the live documentation based on a webhook.

Thanks @futuro!
