### ISSUE TITLE
setup_nightcode_new link to nightcode website isn't a hyperlink

### ISSUE THREAD

**Issue by futuro** [clojurebridge-minneapolis/installfest#41]
https://github.com/clojurebridge-minneapolis/installfest/blob/master/docs/setup_new_nightcode.md doesn't render the link to `https://sekao.net/nightcode/`.

**Comment by tmarble** [comment]
Okay this is part of the "Experimental" instructions that must go away.
The nightcode specific stuff should live in the "Instructions by operating system"

```
## Instructions by operating system

Choose your operating system to get setup instructions:

* [OS X](setup_osx.md)
* [Windows 7](setup_win7.md)
* [Windows 8](setup_win8.md)
* [Linux](setup_ubuntu.md)
```

NOTE @skoestler this means your recent fixes need to move too.
