### ISSUE TITLE
Verify JDK8 install on Mac

### ISSUE THREAD

**Issue by tmarble** [clojurebridge-minneapolis/installfest#9]
We need to check the URL's, verify the install procedure, etc.

See also:
https://github.com/clojurebridge-minneapolis/installfest/blob/experimental/docs/setup_new_java.md 

Will contribute to #8

**Comment by mulchy** [comment]
I install Java on my machines by using homebrew cask. Once homebrew is installed, it should be as easy as `brew cask install java`. I don't know if this is easier or harder than clicking through the Oracle download, but it might be something to consider.

**Comment by mulchy** [comment]
Wait, do we even ask them to install homebrew?

**Comment by tmarble** [comment]
TBQH it's been a long time since I've had a functioning MacBook and tried to do dev on Mac OS X... I'll let you use your judgement (between Oracle, homebrew, MacPorts -- which was a thing many years ago, and/or Xcode, ???)

**Comment by mulchy** [comment]
This is still assigned to me, but let it be known that @skoestler actually did all the work!
